In [1]:
#!/usr/bin/env python
import requests
data = {
    'token': '9C5F7D13A99C4CB606335649B7D2858D',
    'content': 'record',
    'action': 'export',
    'format': 'csv',
    'type': 'flat',
    'csvDelimiter': '',
    'fields[0]': 'student_tracking_id',
    'fields[1]': 'age',
    'fields[2]': 'sex',
    'fields[3]': 'school',
    'rawOrLabel': 'raw',
    'rawOrLabelHeaders': 'raw',
    'exportCheckboxLabel': 'false',
    'exportSurveyFields': 'false',
    'exportDataAccessGroups': 'false',
    'returnFormat': 'csv'
}
r = requests.post('https://redcap.ucsf.edu/api/',data=data)
print('HTTP Status: ' + str(r.status_code))

HTTP Status: 200

In [2]:
import pandas as pd
from io import StringIO
df = pd.read_csv(StringIO(r.text))
df

     student_tracking_id redcap_event_name  age  sex  school
0                      1    fall2021_arm_1  7.0  0.0     0.0
1          77_21-G1_0901    fall2021_arm_1  NaN  NaN    20.0
2          77_21-G1_0902    fall2021_arm_1  NaN  NaN    20.0
3          77_21-G1_0902  winter2022_arm_1  NaN  NaN     NaN
4          77_21-G1_0903    fall2021_arm_1  NaN  NaN    20.0
...                  ...               ...  ...  ...     ...
6331   77_23_VAL_KG_0199    fall2021_arm_1  NaN  NaN    31.0
6332   77_23_VAL_KG_0199  winter2022_arm_1  NaN  NaN     NaN
6333   77_23_VAL_KG_0200    fall2021_arm_1  NaN  NaN    31.0
6334   77_23_VAL_KG_0200  winter2022_arm_1  NaN  NaN     NaN
6335      77_TRB_G1_0063  winter2022_arm_1  NaN  NaN     NaN

[6336 rows x 5 columns]